### PR TITLE
Support Python 3.8

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Odd, lots of tests fail, even for things I haven't touched (e.g.: Python 2.7).

Could this be some dependency that needs pinning?

**Comment by WhyNotHugo** [comment]
Huh, I've triggered a run of `master`, and that fails too: https://travis-ci.com/github/WhyNotHugo/django-payments/jobs/365900394

My guess is that yes, some library has been updated and needs to be pinned to an older version.

**Comment by WhyNotHugo** [comment]
Figured out why master is broken: the test credit cards have expired!

I'll try to figure out how to update the relevant tests!

**Comment by WhyNotHugo** [comment]
CI is failing only due to coverage missing for a line with a minor fix.

Is that a blocker? I can drop the last commit if that's the case.

**Comment by patrys** [comment]
@WhyNotHugo No, it's fine, I'm waiting for LGTM to finish and will merge this if nothing comes up!

**Comment by WhyNotHugo** [comment]
Thanks!

**Pull request merged**
