### PR TITLE
Features/sofort

### PR DESCRIPTION
**Pull request by illing2005**
Add sofort.com backend

### CODE REVIEW

**Comment by patrys** [comment]
Does the gateway offer a testing/sandbox environment? If so, would you mind setting the default endpoint to point to that?

**Comment by illing2005** [comment]
The testing environment uses the same endpoint, but has to be activated on their online portal.  
To make test transfers one has to enter	bank code number 88888888 and then follow the instructions.

**Comment by patrys** [comment]
Thanks for your contribution! Would you like to add basic test coverage?

**Comment by illing2005** [comment]
You're welcome. 
I was trying to write some tests, but somehow I can't load the templates in running your testsuite.
I'm always getting the following error:
"TemplateDoesNotExist: payments/sofort/new_transaction.xml"
This is because I use the "render_to_string" method. Somehow the testsuite can't find the template. 

I use this command to run the tests:
python setup.py test

Do you know how to fix this?

**Pull request merged**
